Import test and bugfixes.
Pronovix/devportal-drupal-module pull request #37
Opened 2018-07-19 08:31 UTC by tamasd

2018-07-19 08:51 UTC, peterserfozo requested changes

2018-07-19 08:51 UTC, peterserfozo commented on modules/repo_sync/tests/src/Functional/ImportTest.php
> +    $this->drupalPostForm('/admin/devportal/repo-sync/create', [
Use `Url::fromRoute(route_name)` instead of path.

2018-07-19 08:51 UTC, peterserfozo commented on modules/repo_sync/tests/src/Functional/ImportTest.php
> +    $this->drupalPostForm('/admin/devportal/repo-sync/create', [
Use `Url::fromRoute(route_name)` instead of path.

2018-07-19 08:51 UTC, peterserfozo commented on modules/repo_sync/tests/src/Functional/ImportTest.php
> +    $installer = \Drupal::service('module_installer');
Use `$this->container->get('service_name')` instead of `\Drupal::service()`.

2018-07-19 08:51 UTC, peterserfozo commented on modules/repo_sync/tests/src/Functional/ImportTest.php
> +    $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple();
Use `$this->container->get('entity_type.manager')` instead of `\Drupal::entityTypeManager()`.

2018-07-19 08:51 UTC, peterserfozo commented on modules/repo_sync/tests/src/Functional/RepoSyncTestBase.php
> +    \Drupal::configFactory()->getEditable('devportal_repo_sync.config')
Use `$this->config('devportal_repo_sync.config')->set()`.

2018-07-19 08:51 UTC, peterserfozo commented on modules/repo_sync/tests/src/Functional/RepoSyncTestBase.php
> +    $connection = \Drupal::service('devportal_repo_sync.connection');
`$this->container->get()`

2018-07-19 08:51 UTC, peterserfozo commented on tests/src/Functional/DevportalTestBase.php
> +    $client = \Drupal::httpClient();
`$this->container->get()`

2018-07-19 08:51 UTC, peterserfozo commented on tests/src/Functional/DevportalTestBase.php
> +    $request = \Drupal::request();
`$this->container->get('request_stack')->getCurrentRequest()`

2018-07-19 08:51 UTC, peterserfozo commented on tests/src/Functional/DevportalTestBase.php
> +    $queue = \Drupal::queue($name);
`$this->container->get()`

2018-07-19 08:51 UTC, peterserfozo commented on tests/src/Functional/DevportalTestBase.php
> +    $manager = \Drupal::service('plugin.manager.queue_worker');
`$this->container->get()`

2018-07-19 09:19 UTC, mxr576 requested changes

2018-07-19 09:19 UTC, mxr576 commented on modules/api_reference/devportal_api_reference.info.yml
> +  - drupal:menu_ui
Why do you need the menu_ui?

2018-07-19 09:19 UTC, mxr576 commented on modules/repo_sync/tests/src/Functional/ImportTest.php
> +    $repo_url = 'https://github.com/tamasd/git-test.git';
The repo url could be a constant.

2018-07-19 09:19 UTC, mxr576 commented on modules/repo_sync/tests/src/Functional/ImportTest.php
> +    $installer->install(['devportal_api_reference']);
Router may needs to be rebuild after you enabled a module.
https://github.com/apigee/apigee-edge-drupal/blob/fe6f716c193c5487fa162ee285dcb3ccee4d5085/tests/src/Functional/ApigeeEdgeTestTrait.php#L319

2018-07-19 09:25 UTC, balazswmann approved these changes

2018-07-19 11:05 UTC, tamasd commented on modules/api_reference/devportal_api_reference.info.yml
> +  - drupal:menu_ui
To fix this:
```Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for node.type.api_reference with the following errors: node.type.api_reference:third_party_settings.menu_ui.available_menus missing schema, node.type.api_reference:third_party_settings.menu_ui.parent missing schema```

2018-07-19 11:12 UTC, peterserfozo approved these changes

2018-07-19 11:48 UTC, lekob approved these changes

2018-07-20 12:06 UTC, mxr576 approved these changes

2018-07-20 12:09 UTC, merged