Add dev/test environment from the Drupal module template
Pronovix/devportal-drupal-module pull request #73
Opened 2019-06-27 11:20 UTC by mxr576

Licensing in the files copied from the template still needs to be discussed.

2019-07-05 11:50 UTC, tamasd submitted a review, later dismissed

2019-07-08 07:26 UTC, boobaa requested changes
Also, is it absolutely necessary to commit `.dev/testrunner` which is a blob and if I'm not mistaken, it's pulled in from its source when needed?

2019-07-08 07:26 UTC, boobaa commented on modules/dp_faq/dp_faq.module
>    if ($form["#id"] === 'views-exposed-form-devportal-faq-page-1') {
Could you pls also fix these double apostrophes to single ones while you're there?

2019-07-08 11:52 UTC, boobaa approved these changes

2019-07-08 12:16 UTC, tamasd approved these changes

2019-07-08 12:21 UTC, merged